require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MlpQueriesController do

  # This should return the minimal set of attributes required to create a valid
  # MlpQuery. As you add validations to MlpQuery, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "session" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MlpQueriesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all mlp_queries as @mlp_queries" do
      mlp_query = MlpQuery.create! valid_attributes
      get :index, {}, valid_session
      assigns(:mlp_queries).should eq([mlp_query])
    end
  end

  describe "GET show" do
    it "assigns the requested mlp_query as @mlp_query" do
      mlp_query = MlpQuery.create! valid_attributes
      get :show, {:id => mlp_query.to_param}, valid_session
      assigns(:mlp_query).should eq(mlp_query)
    end
  end

  describe "GET new" do
    it "assigns a new mlp_query as @mlp_query" do
      get :new, {}, valid_session
      assigns(:mlp_query).should be_a_new(MlpQuery)
    end
  end

  describe "GET edit" do
    it "assigns the requested mlp_query as @mlp_query" do
      mlp_query = MlpQuery.create! valid_attributes
      get :edit, {:id => mlp_query.to_param}, valid_session
      assigns(:mlp_query).should eq(mlp_query)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MlpQuery" do
        expect {
          post :create, {:mlp_query => valid_attributes}, valid_session
        }.to change(MlpQuery, :count).by(1)
      end

      it "assigns a newly created mlp_query as @mlp_query" do
        post :create, {:mlp_query => valid_attributes}, valid_session
        assigns(:mlp_query).should be_a(MlpQuery)
        assigns(:mlp_query).should be_persisted
      end

      it "redirects to the created mlp_query" do
        post :create, {:mlp_query => valid_attributes}, valid_session
        response.should redirect_to(MlpQuery.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved mlp_query as @mlp_query" do
        # Trigger the behavior that occurs when invalid params are submitted
        MlpQuery.any_instance.stub(:save).and_return(false)
        post :create, {:mlp_query => { "session" => "invalid value" }}, valid_session
        assigns(:mlp_query).should be_a_new(MlpQuery)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        MlpQuery.any_instance.stub(:save).and_return(false)
        post :create, {:mlp_query => { "session" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested mlp_query" do
        mlp_query = MlpQuery.create! valid_attributes
        # Assuming there are no other mlp_queries in the database, this
        # specifies that the MlpQuery created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        MlpQuery.any_instance.should_receive(:update_attributes).with({ "session" => "MyString" })
        put :update, {:id => mlp_query.to_param, :mlp_query => { "session" => "MyString" }}, valid_session
      end

      it "assigns the requested mlp_query as @mlp_query" do
        mlp_query = MlpQuery.create! valid_attributes
        put :update, {:id => mlp_query.to_param, :mlp_query => valid_attributes}, valid_session
        assigns(:mlp_query).should eq(mlp_query)
      end

      it "redirects to the mlp_query" do
        mlp_query = MlpQuery.create! valid_attributes
        put :update, {:id => mlp_query.to_param, :mlp_query => valid_attributes}, valid_session
        response.should redirect_to(mlp_query)
      end
    end

    describe "with invalid params" do
      it "assigns the mlp_query as @mlp_query" do
        mlp_query = MlpQuery.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MlpQuery.any_instance.stub(:save).and_return(false)
        put :update, {:id => mlp_query.to_param, :mlp_query => { "session" => "invalid value" }}, valid_session
        assigns(:mlp_query).should eq(mlp_query)
      end

      it "re-renders the 'edit' template" do
        mlp_query = MlpQuery.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MlpQuery.any_instance.stub(:save).and_return(false)
        put :update, {:id => mlp_query.to_param, :mlp_query => { "session" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested mlp_query" do
      mlp_query = MlpQuery.create! valid_attributes
      expect {
        delete :destroy, {:id => mlp_query.to_param}, valid_session
      }.to change(MlpQuery, :count).by(-1)
    end

    it "redirects to the mlp_queries list" do
      mlp_query = MlpQuery.create! valid_attributes
      delete :destroy, {:id => mlp_query.to_param}, valid_session
      response.should redirect_to(mlp_queries_url)
    end
  end

end
