require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MlpQueriesController do

  # This should return the minimal set of attributes required to create a valid
  # MlpQuery. As you add validations to MlpQuery, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { mlp_login_email: 'bhf2689@email.vccs.edu',
      section: 72,
      semester: 'FA13',
      class_stop:  Time.new(2013,12,17, 11,30,0),
      class_start: Time.new(2013,11,14,9,30,0),
      session: 'D' } }

  let(:invalid_attributes) { { mlp_login_email: 'bhf2689@email.vccs.edu',
      section: 72,
      semester: 'FA13',
      class_stop:  Time.new(2013,12,17, 11,30,0),
      class_start: Time.new(2013,11,14,9,30,0),
      session: nil } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MlpQueriesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET cold_start (which grabs the last MlpQuery to start from)", focus: true do
    it "assigns last MlpQuery as @mlp_query" do
      mlp_query = MlpQuery.create! valid_attributes
      mlp_query2 = MlpQuery.create! valid_attributes
      get :cold_start, {}, valid_session
      assigns(:mlp_query).should eq(mlp_query2)
    end
    it "assigns a default MlpQuery to @mlp_queries if none exist"  do
      # nothing created so MlpQuery.last = nil
      get :cold_start, {}, valid_session
      my_mq = MlpQuery.new valid_attributes ; my_mq.id = 1 # need to set the id as well to satisfy eql
      expect(assigns(:mlp_query)).to eql(my_mq)
    end
    it "renders the :edit view" do
      get :cold_start, {}, valid_session
      expect(response).to render_template :edit
    end
  end

  describe "GET index" do
    it "assigns all mlp_queries as @mlp_queries" do
      mlp_query = MlpQuery.create! valid_attributes
      mlp_query2 = MlpQuery.create! valid_attributes
      get :index, {}, valid_session
      assigns(:mlp_queries).should eq([mlp_query, mlp_query2])
    end
  end

  describe "GET show" do
    it "assigns the requested mlp_query as @mlp_query" do
      mlp_query = MlpQuery.create! valid_attributes
      get :show, {:id => mlp_query.to_param}, valid_session
      assigns(:mlp_query).should eq(mlp_query)
    end
  end

  describe "GET show using expect" do
    it "assigns the requested mlp_query as @mlp_query" do
      mlp_query = MlpQuery.create! valid_attributes
      get :show, {:id => mlp_query.to_param}, valid_session
      expect(assigns(:mlp_query)).to eq mlp_query
    end

    it "renders the :show template" do
      mlp_query = MlpQuery.create! valid_attributes
      get :show, {:id => mlp_query.to_param}, valid_session
      expect(response).to render_template :show
    end
  end

  describe "GET new" do
    it "assigns a new mlp_query as @mlp_query" do
      get :new, {}, valid_session
      assigns(:mlp_query).should be_a_new(MlpQuery)
    end
  end

  describe "GET edit" do
    it "assigns the requested mlp_query as @mlp_query" do
      mlp_query = MlpQuery.create! valid_attributes
      get :edit, {:id => mlp_query.to_param}, valid_session
      assigns(:mlp_query).should eq(mlp_query)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MlpQuery" do
        expect {
          post :create, {:mlp_query => valid_attributes}, valid_session
        }.to change(MlpQuery, :count).by(1)
      end

      it "assigns a newly created mlp_query as @mlp_query" do
        post :create, {:mlp_query => valid_attributes}, valid_session
        assigns(:mlp_query).should be_a(MlpQuery)
        assigns(:mlp_query).should be_persisted
      end

      it "redirects to the created mlp_query" do
        post :create, {:mlp_query => valid_attributes}, valid_session
        response.should redirect_to(MlpQuery.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved mlp_query as @mlp_query" do
        # Trigger the behavior that occurs when invalid params are submitted
        MlpQuery.any_instance.stub(:save).and_return(false)
        post :create, {:mlp_query => { "session" => "invalid value" }}, valid_session
        assigns(:mlp_query).should be_a_new(MlpQuery)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        MlpQuery.any_instance.stub(:save).and_return(false)
        post :create, {:mlp_query => { "session" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested mlp_query" do
        mlp_query = MlpQuery.create! valid_attributes
        # Assuming there are no other mlp_queries in the database, this
        # specifies that the MlpQuery created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        MlpQuery.any_instance.should_receive(:update_attributes).with({ "session" => "MyString" })
        put :update, {:id => mlp_query.to_param, :mlp_query => { "session" => "MyString" }}, valid_session
      end

      it "assigns the requested mlp_query as @mlp_query" do
        mlp_query = MlpQuery.create! valid_attributes
        put :update, {:id => mlp_query.to_param, :mlp_query => valid_attributes}, valid_session
        assigns(:mlp_query).should eq(mlp_query)
      end

      it "redirects to the mlp_query with explicit :action" do
        mlp_query = MlpQuery.create! valid_attributes
        put :update, {:id => mlp_query.to_param, :mlp_query => valid_attributes}, valid_session
        response.should redirect_to action: :show, id: assigns(:mlp_query).id
      end
    end

    describe "with invalid params" do
      it "assigns the mlp_query as @mlp_query" do
        mlp_query = MlpQuery.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MlpQuery.any_instance.stub(:save).and_return(false)
        put :update, {:id => mlp_query.to_param, :mlp_query => { "session" => "invalid value" }}, valid_session
        assigns(:mlp_query).should eq(mlp_query)
      end

      it "re-renders the 'edit' template" do
        mlp_query = MlpQuery.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MlpQuery.any_instance.stub(:save).and_return(false)
        put :update, {:id => mlp_query.to_param, :mlp_query => { "session" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested mlp_query" do
      mlp_query = MlpQuery.create! valid_attributes
      expect {
        delete :destroy, {:id => mlp_query.to_param}, valid_session
      }.to change(MlpQuery, :count).by(-1)
    end

    it "redirects to the mlp_queries list" do
      mlp_query = MlpQuery.create! valid_attributes
      delete :destroy, {:id => mlp_query.to_param}, valid_session
      response.should redirect_to(mlp_queries_url)
    end
  end

  # non HTTP routes
  describe "#request_table" do
    it "renders the the :request_table template" do
      mlp_query = MlpQuery.create! valid_attributes
      get :request_table, {:id => mlp_query.to_param}, valid_session
      expect(response).to render_template :request_table
    end
    it "assigns the requested mlp_query as @mlp_query" do
      mlp_query = MlpQuery.create! valid_attributes
      mlp_query2 = MlpQuery.create! valid_attributes
      get :request_table, {:id => mlp_query2.to_param}, valid_session
      assigns(:mlp_query).should eq(mlp_query2)
      expect(assigns(:email)).to eq(mlp_query2[:mlp_login_email])
    end
  end

  describe "#display_table" do
    it "sends :results to @mlp_query" do
      pending "have not gotten the syntax right yet!"
      mlp_query = MlpQuery.create! valid_attributes
      get :display_table, {:id => mlp_query.to_param, :pswd => "test"}, valid_session
      expect(:mlp_query).to receive(:results).once
    end
   it "renders the :display_table template" do
      mlp_query = MlpQuery.create! valid_attributes
      MlpQuery.any_instance.stub(:results).and_return('Login did not fail and results_hash was returned!')
      get :display_table, {:id => mlp_query.to_param, :pswd => "test"}, valid_session
      expect(response).to render_template :display_table
    end
    it "redirects to :edit if login fails" do
      mlp_query = MlpQuery.create! valid_attributes
      # Trigger the behavior that occurs when invalid params are submitted
      MlpQuery.any_instance.stub(:results).and_return('login failed - please confirm MLP login email and password')
      get :display_table, {:id => mlp_query.to_param, :pswd => "test"}, valid_session
      expect(response).to render_template :edit
    end
    it "redirects to :edit if no mte courses match the query parameters" do
    end
  end

end
